# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kolejka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hostGoals', models.IntegerField()),
                ('guestGoals', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incydent', models.CharField(max_length=300)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Team'),
        ),
        migrations.AddField(
            model_name='table',
            name='name1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.LeagueType'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Team'),
        ),
        migrations.AddField(
            model_name='matchfacts',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MatchGuest', to='competition.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_host', to='competition.Team'),
        ),
        migrations.AddField(
            model_name='kolejka',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Match'),
        ),
        migrations.AddField(
            model_name='kolejka',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.LeagueType'),
        ),
    ]
