# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, default='2018-01-06', null=True),
        ),
        migrations.AlterField(
            model_name='matchfacts',
            name='incident',
            field=models.CharField(choices=[('none', 'none'), ('goal', 'goal'), ('sub in', 'sub in'), ('sub out', 'sub out'), ('yellow card', 'yellow card'), ('red card', 'red card')], default='none', max_length=15),
        ),
    ]
