# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 16:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20171108_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchfacts',
            name='minute',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
            preserve_default=False,
        ),
    ]
