# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 22:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20180104_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalsScored', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('goalsLost', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('matchesWon', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('matchesLost', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('matchesDraw', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('scores', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.LeagueType')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Team')),
            ],
        ),
    ]
