# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 15:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20180106_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goalsScored', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.Season')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, default='2018-01-10', null=True),
        ),
    ]
