# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_matchfacts_minute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguetype',
            old_name='name1',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='matchfacts',
            name='incident',
            field=models.CharField(choices=[('none', 'brak'), ('goal', 'gol'), ('sub in', 'zmiania wchodzi'), ('sub out', 'zmiana zchodzi'), ('yelow card', 'zolta kartka'), ('red card', 'czerwona kartka')], default='none', max_length=15),
        ),
    ]
