# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_teamstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(blank=True, default='2018-01-05', null=True),
        ),
    ]
