# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20180105_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.ImageField(default=1, upload_to='media/avatars'),
            preserve_default=False,
        ),
    ]
