# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 07:26
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='guest',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='league', chained_model_field='league', on_delete=django.db.models.deletion.CASCADE, related_name='MatchGuest', to='competition.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='host',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='league', chained_model_field='league', on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_host', to='competition.Team'),
        ),
    ]
